### ISSUE TITLE
unable to find animation speed

### ISSUE THREAD

**Issue by rcrath** [rcrath/TW5-TabStory#3]
@Jermolene wrote 

> By the way, you may want to set the animation speed to zero to remove the animation when switching tabs.

I was not able to find this setting.

**Comment by Jermolene** [comment]
Hi @rcrath the animation speed setting is in the "Info"/"Basics" tab of control panel.

**Comment by rcrath** [comment]
@Jermolene lol, thanks I looked in all the tabs but the first one. doh.
